" 編輯器喜好設定 
set nu
set ai
set tabstop=4
set shiftwidth=4
set cursorline
set cursorcolumn
set nocompatible

" 解決delete鍵失效問題
et backspace=2

" Color configuration
syntax enable
set bg=dark
"colorscheme solarized
