" 編輯器喜好設定      
set nu
set ai
set tabstop=4
set shiftwidth=4
set cursorline
set cursorcolumn
set nocompatible 

" Color configuration
syntax enable 
if has('gui_running')
    set background=light
else
    set background=dark
endif
colorscheme solarized
